codecov:
  allow_coverage_offsets: true

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project: off
    patch:
      default: off
      json:
        flags: json
        only_pulls: true
        target: 50%
        threshold: 10%
      gojay:
        flags: gojay
        only_pulls: true
        target: 50%
        threshold: 10%
    changes:
      default: off
      json:
        flags: json
        target: auto
        threshold: 10%
        if_not_found: success
        if_ci_failed: error
      gojay:
        flags: gojay
        target: auto
        threshold: 10%
        if_not_found: success
        if_ci_failed: error

flags:
  json:
    paths:
      - /
    carryforward: true
  gojay:
    paths:
      - /
    carryforward: true

ignore:
  - "internal/gojaypool/gojaypool.go"

comment:
  behavior: default
  show_carryforward_flags: true

github_checks:
  annotations: true
