run:
  issues-exit-code: 1
  tests: true
  # skip-dirs:
  skip-dirs-use-default: true
  skip-files:
    - ".*\\.pb\\.go"
    - ".*(.|_)gen\\.go"
  modules-download-mode: vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: false
    check-blank: true
    exclude: .errcheckignore
  funlen:
    lines: 60
    statements: 40
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 128
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: go.lsp.dev/protocol
  golint:
    min-confidence: 0.3
  govet:
    enable:
      - asmdecl
      - assign
      - atomic
      - atomicalign
      - bools
      - buildtag
      - cgocall
      - composite
      - copylock
      - deepequalerrors
      - errorsas
      - findcall
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - shift
      - sortslice
      - stdmethods
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - shadow
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      # - github.com/sirupsen/logrus
    packages-with-error-message:
      # - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  lll:
    line-length: 120
    tab-width: 1
  maligned:
    suggest-new: false
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    check-exported: true
    algo: cha
  unused:
    check-exported: false
  whitespace:
    multi-if: true
    multi-func: true
  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-cuddle-declarations: true  # default: false
    allow-trailing-comment: true  # default: false
    force-case-trailing-whitespace: 0  # default: 0 = never
    force-err-cuddling: true  # default: false
    allow-separated-leading-comment: true  # default: false

linters:
  fast: false
  # disabled:
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - godox
    # - gomnd
    # - gosec
    # - lll
    # - maligned
    # - megacheck
    # - scopelint
    # - wsl
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - lll
    - path: _test\.go
      text: "rangeValCopy"
      linters:
        - gocritic
    - path: language.go
      text: "deprecatedComment"
      linters:
        - gocritic
    - linters:
        - gocognit
      text: "TextDocumentClientCapabilities"
    - linters:
        - gocognit
        - gocyclo
      text: "ServerHandler"
    - linters:
        - gocognit
        - gocyclo
      text: "ClientHandler"
    - linters:
        - gocyclo
      text: "UnmarshalJSONObject"
    - path: language.go
      text: "func `\\(SymbolKind\\).String` is high"
      linters:
        - gocyclo
    - path: language.go
      text: "func `\\(CompletionItemKind\\).String` is high"
      linters:
        - gocyclo
