run:
  concurrency: 12
  deadline: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - "internal"
  skip-files:
    - ".*\\.pb\\.go"
  modules-download-mode: vendor

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: true
    exclude: .errcheckignore
  goconst:
    min-len: 3
    min-occurrences: 3
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/go-language-server/protocol/
  golint:
    min-confidence: 0.3
  govet:
    check-shadowing: false
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    algo: cha
    check-exported: true
  unused:
    check-exported: true

linters:
  enable:
    - deadcode
    - depguard
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - ineffassign
    - misspell
    - prealloc
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - gosimple
    - govet
    - interfacer
    - staticcheck
    - stylecheck
    - unparam
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - lll
    - maligned
    - nakedret
    - scopelint
    - unused
  fast: true

issues:
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
