version: 2.1

orbs:
  golang: cci-orb/golang@volatile
  codecov: codecov/codecov@volatile

jobs:
  test:
    parameters:
      go-version:
        type: string
    executor:
      name: golang/linux
      version: "<< parameters.go-version >>"
    working_directory: /go/src/go.lsp.dev/protocol
    resource_class: large
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Test and collect coverages
          command: |
            make $(circleci tests split .circleci/coverage-targets)
      - codecov/upload:
          file: "/tmp/ci/artifacts/coverage.out"
          flags: $(if [ $CIRCLE_NODE_INDEX == 0 ]; then echo "json"; else echo "gojay"; fi)
      - store_artifacts:
          path: /tmp/ci/artifacts
      - store_test_results:
          path: /tmp/ci/artifacts
      - store_test_results:
          path: /tmp/ci/test-results

  lint:
    parameters:
      go-version:
        type: string
    executor:
      name: golang/linux
      version: "<< parameters.go-version >>"
    working_directory: /go/src/go.lsp.dev/protocol
    resource_class: large
    parallelism: 2
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run lint for sources
          command: |
            make lint GO_LINT_FLAGS=$(circleci tests split .circleci/lint-buildtags)

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
          matrix:
            parameters:
              go-version: ["1.15-buster", "1.16-rc-buster"]
      - lint:
          context: org-global
          matrix:
            parameters:
              go-version: ["1.15-buster", "1.16-rc-buster"]
